### ISSUE TITLE
IOError: [Errno 13] Permission denied:

### ISSUE THREAD

**Issue by zijam** [linuxserver/docker-sickrage#25]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Host OS: Ubuntu 16.04
Dockerfile:
```
  sickrage:
    image: linuxserver/sickrage
    volumes:
      - /home/server/downloads:/downloads
      - /home/server/series:/series/server
    environment:
      PUID: 501
      PGID: 1000
```
```
sickrage_1      | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
sickrage_1      | [s6-init] ensuring user provided files have correct perms...exited 0.
sickrage_1      | [fix-attrs.d] applying ownership & permissions fixes...
sickrage_1      | [fix-attrs.d] done.
sickrage_1      | [cont-init.d] executing container initialization scripts...
sickrage_1      | [cont-init.d] 10-adduser: executing...
sickrage_1      |
sickrage_1      | -------------------------------------
sickrage_1      |           _     _ _
sickrage_1      |          | |___| (_) ___
sickrage_1      |          | / __| | |/ _ \
sickrage_1      |          | \__ \ | | (_) |
sickrage_1      |          |_|___/ |_|\___/
sickrage_1      |                |_|
sickrage_1      |
sickrage_1      | Brought to you by linuxserver.io
sickrage_1      | We gratefully accept donations at:
sickrage_1      | https://www.linuxserver.io/donations/
sickrage_1      | -------------------------------------
sickrage_1      | GID/UID
sickrage_1      | -------------------------------------
sickrage_1      | User uid:    501
sickrage_1      | User gid:    1000
sickrage_1      | -------------------------------------
sickrage_1      |
sickrage_1      | [cont-init.d] 10-adduser: exited 0.
sickrage_1      | [cont-init.d] 30-config: executing...
sickrage_1      | [cont-init.d] 30-config: exited 0.
sickrage_1      | [cont-init.d] done.
sickrage_1      | [services.d] starting services
sickrage_1      | [services.d] done.
sickrage_1      | 18:31:28 INFO::MAIN :: 171501: Unable to find IMDb show info in the database
sickrage_1      | 18:31:28 INFO::MAIN :: Starting SickRage [master] using '/config/config.ini'
sickrage_1      | 18:31:28 INFO::TORNADO :: Starting SickRage on http://0.0.0.0:8081/
.......

error 13 : Permission denied
sickrage_1      | Traceback (most recent call last):
sickrage_1      |   File "/app/sickrage/sickbeard/postProcessor.py", line 373, in _int_move
sickrage_1      |     helpers.moveFile(cur_file_path, new_file_path)
sickrage_1      |   File "/app/sickrage/sickbeard/helpers.py", line 402, in moveFile
sickrage_1      |     ek(shutil.move, srcFile, destFile)
sickrage_1      |   File "/app/sickrage/sickrage/helper/encoding.py", line 43, in ek
sickrage_1      |     result = function(*[ss(x) if isinstance(x, six.string_types) else x for x in args], **kwargs)
sickrage_1      |   File "/usr/lib/python2.7/shutil.py", line 302, in move
sickrage_1      |     copy2(src, real_dst)
sickrage_1      |   File "/usr/lib/python2.7/shutil.py", line 130, in copy2
sickrage_1      |     copyfile(src, dst)
sickrage_1      |   File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
sickrage_1      |     with open(dst, 'wb') as fdst:
sickrage_1      | IOError: [Errno 13] Permission denied: '/series/server/[serie_name].mkv'
sickrage_1      | 18:21:53 WARNING::POSTPROCESSOR-MANUAL :: Processing failed for /downloads/completed/series/[serie_name].mkv:Unable to move the files to their new home
```

I don't understand why I get a Permission denied.
I'm able to create a folder and files in ```/series/server/```, when I jump into the container likes this
```docker exec -it media_sickrage_1  /bin/bash```

**Comment by j0nnymoe** [comment]
looks like user with ID 501 doesn't have permission to write to those folders. I assume these are local folders? not remotely mounted? (NFS/SMB)

**Comment by zijam** [comment]
Yes it is a host folder, but I found the error.
root was owner of the folder 😓.
