### ISSUE TITLE
Errors during start up, files missing from temp

### ISSUE THREAD

**Issue by russell** [linuxserver/docker-sickrage#6]
Not sure what is going on but during the boot up there are a bunch of errors thrown from pip.  Everything still works but it's not ideal that theses errors exist.

```
sickrage_1 |       Successfully uninstalled virtualenv-13.1.2
sickrage_1 | Exception:
sickrage_1 | Traceback (most recent call last):
sickrage_1 |   File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 211, in main
sickrage_1 |     status = self.run(options, args)
sickrage_1 |   File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 311, in run
sickrage_1 |     root=options.root_path,
sickrage_1 |   File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 657, in install
sickrage_1 |     requirement.commit_uninstall()
sickrage_1 |   File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 729, in commit_uninstall
sickrage_1 |     self.uninstalled.commit()
sickrage_1 |   File "/usr/local/lib/python2.7/dist-packages/pip/req/req_uninstall.py", line 152, in commit
sickrage_1 |     rmtree(self.save_dir)
sickrage_1 |   File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/retrying.py", line 49, in wrapped_f
sickrage_1 |     return Retrying(*dargs, **dkw).call(f, *args, **kw)
sickrage_1 |   File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/retrying.py", line 212, in call
sickrage_1 |     raise attempt.get()
sickrage_1 |   File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/retrying.py", line 247, in get
sickrage_1 |     six.reraise(self.value[0], self.value[1], self.value[2])
sickrage_1 |   File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/retrying.py", line 200, in call
sickrage_1 |     attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
sickrage_1 |   File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 90, in rmtree
sickrage_1 |     onerror=rmtree_errorhandler)
sickrage_1 |   File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
sickrage_1 |     rmtree(fullname, ignore_errors, onerror)
sickrage_1 |   File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
sickrage_1 |     rmtree(fullname, ignore_errors, onerror)
sickrage_1 |   File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
sickrage_1 |     rmtree(fullname, ignore_errors, onerror)
sickrage_1 |   File "/usr/lib/python2.7/shutil.py", line 252, in rmtree
sickrage_1 |     onerror(os.remove, fullname, sys.exc_info())
sickrage_1 |   File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 98, in rmtree_errorhandler
sickrage_1 |     if os.stat(path).st_mode & stat.S_IREAD:
sickrage_1 | OSError: [Errno 2] No such file or directory: '/tmp/pip-7qjmGP-uninstall/usr/local/bin/virtualenv-3.4'
```

```
root@6d67597b4b88:/# ls /tmp/pip-7qjmGP-uninstall/usr/local/bin/ -l
ls: cannot access /tmp/pip-7qjmGP-uninstall/usr/local/bin/virtualenv-3.4: No such file or directory
ls: cannot access /tmp/pip-7qjmGP-uninstall/usr/local/bin/virtualenv: No such file or directory
total 0
c????????? ? ? ? ?            ? virtualenv
c????????? ? ? ? ?            ? virtualenv-3.4
```

**Comment by zaggash** [comment]
Hello,

I tried today, nothing on the log about pip errors.
my /tmp is empty at boot time btw.

Any news on your side ?

**Comment by sparklyballs** [comment]
the pip update script is no longer in baseimage., this error should not be seen anymore.
